name = "glearray"
version = "0.2.0"

description = "Immutable arrays for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "fschwalbe", repo = "glearray" }
links = []

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
